dist: xenial

addons:
  snaps:
  - name: hugo
    channel: extended

# NOTE: Turn off depth flag to access other branches.
git:
  depth: false

before_install:
  - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git clone https://github.com/hugomodo/hugomodo.git ../hugomodo

stages:
  - name: test
  - name: dummy
  - name: standalone
    if: branch = master
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      script:
        - cd ../hugomodo/exampleSite
        - hugo --themesDir ../../ --theme hugomodo-best-motherfucking-website
        # NOTE: We could theoretically get the theme name automatically from the repo slug.
        # Travis provides it as TRAVIS_REPO_SLUG in the form organization/repo
        # We would just need to trim the organization, maybe like so:
        # echo "${TRAVIS_REPO_SLUG/[a-zA-Z-_]*?\//}"
    - stage: standalone
      script:
        - git checkout standalone
        - git reset master --hard
        - rm -f config.toml
        - cp -rn ../hugomodo/. . || true # TODO: cp returns non-zero exit code but appears to succeed regardless
        - git add -A
        - git commit -m "rebuild from master"
        - git push origin standalone --force
    - stage: deploy
      script:
        - release_branch=$(echo ${TRAVIS_TAG} | cut -b 2-)
        - git checkout -b $release_branch
        - git push -u origin $release_branch
        - git checkout standalone
        - standalone_release_branch=$(echo ${TRAVIS_TAG} | cut -b 2- | awk '{print $1"-standalone"}')
        - git checkout -b $standalone_release_branch
        - git push -u origin $standalone_release_branch
